# Generated by Django 2.1.4 on 2019-02-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ec2Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('instance_type', models.CharField(max_length=200, null=True)),
                ('tags', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True)),
                ('default_display', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
                ('start_hour', models.IntegerField(null=True)),
                ('start_minute', models.IntegerField(null=True)),
                ('stop_hour', models.IntegerField(null=True)),
                ('stop_minute', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('instances', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.SchedulesInfo')),
            ],
        ),
        migrations.AddField(
            model_name='schedulesdetails',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.SchedulesInfo'),
        ),
        migrations.AddField(
            model_name='ec2instances',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Regions'),
        ),
    ]
